%% exampleSubjectWaveform.m
% Plot one subject-level ERP waveform using the shared REWP data.

clear;
clc;

thisDir = fileparts(mfilename('fullpath'));
cd(thisDir);

dataFile = fullfile('..', 'sLoretta', 'rewpGrandERP.mat');
chanlocsFile = fullfile('..', 'sLoretta', 'matlocs.mat');

outputs = doWaveForms(dataFile, ...
    'DataVariable', 'grandERP', ...
    'ChanlocsFile', chanlocsFile, ...
    'SubjectIdx', 1, ...
    'ConditionPair', [1 2], ...
    'ConditionLabels', {'Win', 'Loss'}, ...
    'Channels', {'FCz'}, ...
    'StartTime', -200, ...
    'SamplingRate', 500, ...
    'OutputDir', 'outputs', ...
    'OutputPrefix', 'rewp_sub01_cond01minus02_FCz');

fprintf('\nDone.\n');
fprintf('Waveform image:\n%s\n\n', outputs.imageFile);
fprintf('Waveform CSV:\n%s\n\n', outputs.csvFile);
fprintf('Waveform MAT:\n%s\n\n', outputs.matFile);
