%% exampleGroupWaveform.m
% Plot a group-level condition 1 - condition 2 ERP waveform.

clear;
clc;

thisDir = fileparts(mfilename('fullpath'));
cd(thisDir);

dataFile = 'sampleGrandERP.mat';
chanlocsFile = 'sampleGrandERP.mat';

outputs = doGroupWaveForms(dataFile, ...
    'DataVariable', 'sampleGrandERP', ...
    'ChanlocsFile', chanlocsFile, ...
    'ConditionPair', [1 2], ...
    'ConditionLabels', {'Win', 'Loss'}, ...
    'Channels', {'FCz'}, ...
    'StartTime', -200, ...
    'SamplingRate', 500, ...
    'OutputDir', 'outputs', ...
    'OutputPrefix', 'sample_group_cond01minus02_FCz');

fprintf('\nDone.\n');
fprintf('Group waveform image:\n%s\n\n', outputs.imageFile);
fprintf('Group time statistics CSV:\n%s\n\n', outputs.csvFile);
fprintf('Group waveform MAT:\n%s\n\n', outputs.matFile);
fprintf('Peak detection stats CSV:\n%s\n\n', outputs.peakStatsCsvFile);
